
export const USER_LOGIN = "/users/login"
export const ME = "/users/me"
export const CLINICS = "/clinics"
export const CLIENTS = "/clients"
export const STAFF = "/staff"
export const MEDICINE = "/medicine"
export const RESERVATION = "/reservation"
export const ANIMALS = "/animals"
export const CONSUMABLES = "/consumables"
export const CLINIC_CONSUMABLE = "/clinics-consumable"